# Export router — PDF and Markdown export of analysis results
import logging
import json
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from typing import Optional, Any

router = APIRouter()
logger = logging.getLogger(__name__)

DISCLAIMER_TEXT = (
    "\n\n---\n"
    "⚠️ IMPORTANT DISCLAIMER: This document was generated by LegalLens, an AI assistant. "
    "It contains general information only and does NOT constitute legal advice. "
    "This analysis does not create an attorney-client relationship. "
    "For decisions with real legal consequences, always consult a licensed attorney in your jurisdiction.\n"
)


class ExportRequest(BaseModel):
    title: str = "LegalLens Analysis"
    content: Any  # The analysis data to export
    format: str = "markdown"  # "markdown" or "pdf"
    document_name: Optional[str] = None


def _analysis_to_markdown(title: str, content: Any, document_name: Optional[str] = None) -> str:
    """Convert analysis result dict to readable Markdown."""
    lines = [f"# {title}\n"]
    if document_name:
        lines.append(f"**Document:** {document_name}\n")
    lines.append(f"**Generated by:** LegalLens AI Assistant\n")
    lines.append(DISCLAIMER_TEXT)

    if isinstance(content, dict):
        for key, value in content.items():
            if key == "disclaimer":
                continue
            lines.append(f"\n## {key.replace('_', ' ').title()}\n")
            if isinstance(value, list):
                for item in value:
                    if isinstance(item, dict):
                        lines.append("\n---\n")
                        for k, v in item.items():
                            lines.append(f"**{k.replace('_', ' ').title()}:** {v}\n")
                    else:
                        lines.append(f"- {item}\n")
            elif isinstance(value, str):
                lines.append(f"{value}\n")
            else:
                lines.append(f"{json.dumps(value, indent=2)}\n")
    else:
        lines.append(str(content))

    return "\n".join(lines)


@router.post("/markdown")
async def export_markdown(req: ExportRequest):
    """Export analysis as a Markdown document."""
    try:
        md_content = _analysis_to_markdown(req.title, req.content, req.document_name)
        filename = (req.title or "legallens-analysis").lower().replace(" ", "-") + ".md"
        return Response(
            content=md_content,
            media_type="text/markdown",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except Exception as e:
        logger.error(f"Markdown export error: {e}")
        raise HTTPException(status_code=500, detail="Export failed.")


@router.post("/pdf-text")
async def export_pdf_text(req: ExportRequest):
    """
    Return plain text suitable for client-side PDF generation.
    (Full server-side PDF rendering can be added with WeasyPrint/reportlab if needed.)
    """
    try:
        md_content = _analysis_to_markdown(req.title, req.content, req.document_name)
        return {"text": md_content, "title": req.title}
    except Exception as e:
        logger.error(f"PDF text export error: {e}")
        raise HTTPException(status_code=500, detail="Export failed.")
